packages:
  - apps/*

allowBuilds:
  esbuild: true
  lightningcss: true
  sharp: true
  workerd: true
autoInstallPeers: false
minimumReleaseAgeExclude:
  - "@cloudflare/codemods@0.2.1"
  - cf@1.0.0-beta.10
  - wrangler@4.143.0
  - "@cloudflare/vite-plugin@2.0.0-beta.sha-ad79608dd"
overrides:
  "js-yaml@4": 4.3.2
  "undici@7": 7.29.1
